# -*- coding: utf-8 -*-
"""Sayısal Görüntü İşleme Ara Sınavı.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mT7u9zBQ36CDEHfDk6k9RfYHF6NGGCtB

*   TC. ÜSKÜDAR ÜNİVERSİTESİ
*   SAYISAL GÖRÜNTÜ İŞLEME DERSİ
ARA SINAV ÖDEVİ
*   Öğrenci Numarası: 254329031
*   İsim Soyisim: Şahin İnanç ÖZKAYA

#1. Veri Yükleme
##1.1. Kütüphanelerin İçe Aktarılması
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import os
from PIL import Image
from google.colab import drive

"""##1.2. Veri Setinin Yüklenmesi"""

#https://drive.google.com/drive/folders/1tn8SVWSsRGb1jSOzRIKKhcI9veM_oHQO?usp=drive_link

DRIVE_PATH = '/content/drive/MyDrive/skin_cancer'
LOCAL_PATH = '/content/skin_cancer_local'

!cp -r "{DRIVE_PATH}" "{LOCAL_PATH}"

dataset_path = '/content/skin_cancer_local'

data_list = []

for root, dirs, files in os.walk(dataset_path):
    for filename in files:
        if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
            full_path = os.path.join(root, filename)

            label = root.split(os.path.sep)[-1]

            data_list.append({
                'file_path': full_path,
                'label': label
            })

train_df = pd.DataFrame(data_list)

display(train_df.head())

print(f"\nToplam Görüntü Sayısı: {len(train_df)}")

"""#1.3. Veri Özelliklerinin İncelenmesi"""

widths = []
heights = []
channels = []
file_sizes_kb = []

for path in train_df['file_path']:
    try:
        size_bytes = os.path.getsize(path)
        file_sizes_kb.append(size_bytes / 1024)

        img = cv2.imread(path)
        if img is not None:
            h, w, c = img.shape
            heights.append(h)
            widths.append(w)
            channels.append(c)
    except:
        pass

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.scatter(widths, heights, alpha=0.5, c='blue', s=15)
plt.title("Görüntü Çözünürlük Analizi (Yükseklik-Genişlik)")
plt.xlabel("Genişlik (px)")
plt.ylabel("Yükseklik (px)")
plt.grid(True, linestyle='--', alpha=0.5)

plt.subplot(1, 2, 2)
sns.histplot(file_sizes_kb, kde=True, color='green')
plt.title("Dosya Boyutu Dağılımı")
plt.xlabel("Dosya Boyutu (KB)")

plt.tight_layout()
plt.show()

print("\n--- ANALİZ SONUÇLARI ---")
print(f"1. Çözünürlük Analizi:")
print(f"   - Min Çözünürlük: {np.min(heights)}x{np.min(widths)}")
print(f"   - Max Çözünürlük: {np.max(heights)}x{np.max(widths)}")
print(f"   - Ort. Çözünürlük: {int(np.mean(heights))}x{int(np.mean(widths))}")

print(f"\n2. Kanal Sayısı Doğrulaması:")
unique_channels = np.unique(channels)
if len(unique_channels) == 1 and unique_channels[0] == 3:
    print(f"   - SONUÇ: Tüm görüntüler 3 kanallıdır (RGB Formatında).")
else:
    print(f"   - SONUÇ: Farklı kanal sayıları tespit edildi: {unique_channels}")

print(f"\n3. Dosya Boyutu Analizi:")
print(f"   - Ortalama Boyut: {np.mean(file_sizes_kb):.2f} KB")
print(f"   - En Büyük Dosya: {np.max(file_sizes_kb):.2f} KB")

"""#2. Görüntü Yükleme ve Görselleştirme
##2.1. Rastgele Görüntüler Seçme

"""

random9_train_df = train_df.sample(n=9, random_state=50)

fig, axes = plt.subplots(3, 6, figsize=(20, 10))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        row_idx = idx // 3
        col_base_idx = (idx % 3) * 2
        col_rgb_idx = col_base_idx
        col_gray_idx = col_base_idx + 1

        axes[row_idx, col_rgb_idx].imshow(img_rgb)
        axes[row_idx, col_rgb_idx].set_title(f"Örnek {idx+1} (RGB)\n{row['label']}")
        axes[row_idx, col_rgb_idx].axis('off')

        axes[row_idx, col_gray_idx].imshow(img_gray, cmap='gray')
        axes[row_idx, col_gray_idx].set_title(f"Örnek {idx+1} (GRAY)\n{row['label']}")
        axes[row_idx, col_gray_idx].axis('off')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""##2.2. Rastgele Görüntülerin İstatistiksel Özellikleri"""

stats_data = []

for idx, (i, row) in enumerate(random9_train_df.iterrows()):

    img_bgr = cv2.imread(row['file_path'])

    if img_bgr is not None:

        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        rgb_min = np.min(img_rgb)
        rgb_max = np.max(img_rgb)
        rgb_mean = np.mean(img_rgb)
        rgb_std = np.std(img_rgb)

        gray_min = np.min(img_gray)
        gray_max = np.max(img_gray)
        gray_mean = np.mean(img_gray)
        gray_std = np.std(img_gray)

        stats_data.append({
            'Örnek No': idx + 1,
            'Sınıf': row['label'],

            'RGB Min': rgb_min,
            'RGB Max': rgb_max,
            'RGB Ort': f"{rgb_mean:.2f}",
            'RGB Std': f"{rgb_std:.2f}",

            'Gray Min': gray_min,
            'Gray Max': gray_max,
            'Gray Ort': f"{gray_mean:.2f}",
            'Gray Std': f"{gray_std:.2f}"
        })


stats_df = pd.DataFrame(stats_data)

display(stats_df)

"""##2.3. Histogram Çizimi (Zorunlu – RGB + Grayscale)"""

fig, axes = plt.subplots(3, 3, figsize=(20, 16))

axes_flat = axes.ravel()

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    ax = axes_flat[idx]

    if img_bgr is not None:
        colors = ('b', 'g', 'r')

        for channel_id, color in enumerate(colors):
            hist = cv2.calcHist([img_bgr], [channel_id], None, [256], [0, 256])

            ax.plot(hist, color=color, alpha=0.7)
            ax.set_xlim([0, 256])
        ax.set_title(f"Örnek {idx+1} (RGB)\n{row['label']}")
        ax.set_xlabel("Piksel Değeri (0-255)")
        ax.set_ylabel("Frekans (Piksel Sayısı)")
        ax.grid(True, alpha=0.3, linestyle='--')

    else:
        ax.text(0.5, 0.5, "Görüntü Okunamadı", ha='center')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

fig, axes = plt.subplots(3, 3, figsize=(20, 16))
axes_flat = axes.ravel()

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    ax = axes_flat[idx]

    if img_bgr is not None:
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        hist = cv2.calcHist([img_gray], [0], None, [256], [0, 256])

        ax.plot(hist, color='black', alpha=0.9)
        ax.set_xlim([0, 256])

        ax.set_title(f"Örnek {idx+1} (GRAY)\n{row['label']}")
        ax.set_xlabel("Gri Ton Değeri (0:Siyah - 255:Beyaz)")
        ax.set_ylabel("Frekans (Piksel Sayısı)")
        ax.grid(True, alpha=0.3, linestyle='--')

    else:
        ax.text(0.5, 0.5, "Görüntü Okunamadı", ha='center')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""#3. Görüntü İşleme ve İyileştirme
##3.1. Kontrast Germe (Stretching)
"""

def apply_stretching(channel):
    min_val = np.min(channel)
    max_val = np.max(channel)

    if max_val == min_val:
        return channel

    stretched_channel = (channel.astype(float) - min_val) * (255.0 / (max_val - min_val))

    return np.clip(stretched_channel, 0, 255).astype(np.uint8)

fig, axes = plt.subplots(9, 4, figsize=(18, 30))
for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
        stretched_gray = apply_stretching(img_gray)

        b, g, r = cv2.split(img_bgr)
        stretched_r = apply_stretching(r)
        stretched_g = apply_stretching(g)
        stretched_b = apply_stretching(b)
        stretched_rgb = cv2.merge([stretched_b, stretched_g, stretched_r])

        axes[idx, 0].imshow(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))
        axes[idx, 0].set_title(f"Örnek {idx+1} (RGB - Original)\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(cv2.cvtColor(stretched_rgb, cv2.COLOR_BGR2RGB))
        axes[idx, 1].set_title(f"Örnek {idx+1} (RGB - Germe)\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_gray, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} (GRAY - Original)\n{row['label']}")
        axes[idx, 2].axis('off')

        axes[idx, 3].imshow(stretched_gray, cmap='gray')
        axes[idx, 3].set_title(f"Örnek {idx+1} (GRAY - Germe)\n{row['label']}")
        axes[idx, 3].axis('off')

plt.tight_layout()
plt.show()

"""##3.2. Histogram Eşitleme (Equalization)"""

fig, axes = plt.subplots(3, 6, figsize=(20, 10))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:

        img_ycrcb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2YCrCb)
        y, cr, cb = cv2.split(img_ycrcb)
        y_equalized = cv2.equalizeHist(y)
        img_ycrcb_equalized = cv2.merge([y_equalized, cr, cb])
        img_rgb_equalized = cv2.cvtColor(img_ycrcb_equalized, cv2.COLOR_YCrCb2BGR)


        row_idx = idx // 3

        col_orig_idx = (idx % 3) * 2
        col_eq_idx = col_orig_idx + 1

        axes[row_idx, col_orig_idx].imshow(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))
        axes[row_idx, col_orig_idx].set_title(f"Örnek {idx+1} (Original)\n{row['label']}")
        axes[row_idx, col_orig_idx].axis('off')

        axes[row_idx, col_eq_idx].imshow(cv2.cvtColor(img_rgb_equalized, cv2.COLOR_BGR2RGB))
        axes[row_idx, col_eq_idx].set_title(f"Örnek {idx+1} (Eşitlenmiş)\n{row['label']}")
        axes[row_idx, col_eq_idx].axis('off')

    else:
        print(f"Hata: Görüntü okunamadı -> {img_path}")

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(3, 6, figsize=(20, 10))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
        img_gray_equalized = cv2.equalizeHist(img_gray)

        row_idx = idx // 3
        col_orig_idx = (idx % 3) * 2
        col_eq_idx = col_orig_idx + 1

        axes[row_idx, col_orig_idx].imshow(img_gray, cmap='gray')
        axes[row_idx, col_orig_idx].set_title(f"Örnek {idx+1} (Gray - Original)\n{row['label']}")
        axes[row_idx, col_orig_idx].axis('off')

        axes[row_idx, col_eq_idx].imshow(img_gray_equalized, cmap='gray')
        axes[row_idx, col_eq_idx].set_title(f"Örnek {idx+1} (Gray - Eşitlenmiş)\n{row['label']}")
        axes[row_idx, col_eq_idx].axis('off')

    else:
        print(f"Hata: Görüntü okunamadı -> {img_path}")

plt.tight_layout()
plt.show()

"""##3.3. Gamma Düzeltme"""

def apply_gamma(image, gamma):
    inv_gamma = 1.0 / gamma
    table = np.array([((i / 255.0) ** inv_gamma) * 255
                      for i in np.arange(0, 256)]).astype("uint8")

    return cv2.LUT(image, table)

gamma_values = [0.5, 1.0, 2.0]
sample_limit = 9
random9_train_df = train_df.sample(n=sample_limit, random_state=50)

fig, axes = plt.subplots(sample_limit, 3, figsize=(10, 30))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:

        for g_idx, gamma in enumerate(gamma_values):

            img_bgr_gamma = apply_gamma(img_bgr, gamma)
            img_rgb_gamma = cv2.cvtColor(img_bgr_gamma, cv2.COLOR_BGR2RGB)

            col = g_idx

            axes[idx, col].imshow(img_rgb_gamma)
            axes[idx, col].set_title(f"Örnek {idx+1} (RGB - gamma={gamma})\n{row['label']}")
            axes[idx, col].axis('off')


plt.tight_layout()
plt.show()

fig, axes = plt.subplots(sample_limit, 3, figsize=(10, 30))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:

        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY);

        for g_idx, gamma in enumerate(gamma_values):

            img_gray_gamma = apply_gamma(img_gray, gamma)

            col = g_idx

            axes[idx, col].imshow(img_gray_gamma, cmap='gray')
            axes[idx, col].set_title(f"Örnek {idx+1} (GRAY - gamma={gamma})\n{row['label']}")
            axes[idx, col].axis('off')

plt.tight_layout()
plt.show()

"""#4. Gürültü Azaltma
##4.1. Median Blur Uygulama

"""

kernel_size = 5
median_samples = random9_train_df

fig, axes = plt.subplots(9, 4, figsize=(18, 30))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        img_rgb_median = cv2.medianBlur(img_rgb, kernel_size)
        img_gray_median = cv2.medianBlur(img_gray, kernel_size)

        axes[idx, 0].imshow(img_rgb)
        axes[idx, 0].set_title(f"Örnek {idx+1} - RGB - Orijinal\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(img_rgb_median)
        axes[idx, 1].set_title(f"Örnek {idx+1} - RGB - Median Blur\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_gray, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} - GRAY - Orijinal\n{row['label']}")
        axes[idx, 2].axis('off')

        axes[idx, 3].imshow(img_gray_median, cmap='gray')
        axes[idx, 3].set_title(f"Örnek {idx+1} - GRAY - Median Blur\n{row['label']}")
        axes[idx, 3].axis('off')

plt.tight_layout()
plt.show()

"""##4.2. Gaussian Blur Uygulama"""

kernel_size = (5, 5)
sigma_x = 2

gaussian_samples = random9_train_df

fig, axes = plt.subplots(9, 4, figsize=(18, 30))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        img_rgb_gaussian = cv2.GaussianBlur(img_rgb, kernel_size, sigma_x)

        img_gray_gaussian = cv2.GaussianBlur(img_gray, kernel_size, sigma_x)

        axes[idx, 0].imshow(img_rgb)
        axes[idx, 0].set_title(f"Örnek {idx+1} - RGB - Orijinal\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(img_rgb_gaussian)
        axes[idx, 1].set_title(f"Örnek {idx+1} - RGB - Gaussian Blur\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_gray, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} - GRAY - Orijinal\n{row['label']}")
        axes[idx, 2].axis('off')

        axes[idx, 3].imshow(img_gray_gaussian, cmap='gray')
        axes[idx, 3].set_title(f"Örnek {idx+1} - GRAY - Gaussian Blur\n{row['label']}")
        axes[idx, 3].axis('off')

plt.tight_layout()
plt.show()

"""#5. Döndürme ve Ayna Çevirme (Flipping)
##5.1. Rastgele Döndürme

"""

import random

max_angle = 10

rotation_samples = random9_train_df

fig, axes = plt.subplots(9, 2, figsize=(12, 30))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        angle_rgb = random.uniform(-max_angle, max_angle)
        angle_gray = random.uniform(-max_angle, max_angle)

        (h, w) = img_rgb.shape[:2]
        center = (w // 2, h // 2)

        M_rgb = cv2.getRotationMatrix2D(center, angle_rgb, 1.0)
        M_gray = cv2.getRotationMatrix2D(center, angle_gray, 1.0)

        img_rgb_rotated = cv2.warpAffine(img_rgb, M_rgb, (w, h), borderMode=cv2.BORDER_REFLECT)
        img_gray_rotated = cv2.warpAffine(img_gray, M_gray, (w, h), borderMode=cv2.BORDER_REFLECT)

        row_idx = idx
        col_rgb_idx = 0
        col_gray_idx = 1

        axes[row_idx, col_rgb_idx].imshow(img_rgb_rotated)
        axes[row_idx, col_rgb_idx].set_title(f"Örnek {idx+1} - RGB | Açı: {angle_rgb:.2f}°")
        axes[row_idx, col_rgb_idx].axis('off')

        axes[row_idx, col_gray_idx].imshow(img_gray_rotated, cmap='gray')
        axes[row_idx, col_gray_idx].set_title(f"Örnek {idx+1} - GRAY | Açı: {angle_gray:.2f}°")
        axes[row_idx, col_gray_idx].axis('off')

plt.tight_layout()
plt.show()

"""##5.2. Yatay Ayna Çevirme"""

flip_samples = random9_train_df

fig, axes = plt.subplots(9, 4, figsize=(18, 30))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        img_rgb_flipped = cv2.flip(img_rgb, 1)

        img_gray_flipped = cv2.flip(img_gray, 1)

        axes[idx, 0].imshow(img_rgb)
        axes[idx, 0].set_title(f"Örnek {idx+1} - RGB - Orijinal\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(img_rgb_flipped)
        axes[idx, 1].set_title(f"Örnek {idx+1} - RGB - Yatay Flip\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_gray, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} - GRAY - Orijinal\n{row['label']}")
        axes[idx, 2].axis('off')

        axes[idx, 3].imshow(img_gray_flipped, cmap='gray')
        axes[idx, 3].set_title(f"Örnek {idx+1} - GRAY - Yatay Flip\n{row['label']}")
        axes[idx, 3].axis('off')

plt.tight_layout()
plt.show()

"""#6. Frekans Alanında Filtreleme (FFT)
##6.1. Fourier Dönüşümü

"""

fft_samples = random9_train_df

fig, axes = plt.subplots(9, 2, figsize=(12, 36))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:

        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
        img_float32 = np.float32(img_gray)

        dft = np.fft.fft2(img_float32)

        dft_shifted = np.fft.fftshift(dft)

        magnitude_spectrum = 20 * np.log(np.abs(dft_shifted))

        axes[idx, 0].imshow(img_gray, cmap='gray')
        axes[idx, 0].set_title(f"Örnek {idx+1} Gray - Original\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(magnitude_spectrum, cmap='gray')
        axes[idx, 1].set_title(f"Örnek {idx+1} Gray - Log Magnitüd\n{row['label']}")
        axes[idx, 1].axis('off')

plt.tight_layout()
plt.show()

"""##6.2. Alçak Geçiren Filtre Uygulama"""

cutoff_radius = 40

lpf_samples = random9_train_df

fig, axes = plt.subplots(9, 3, figsize=(15, 36))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
        h, w = img_gray.shape

        img_float32 = np.float32(img_gray)
        dft = np.fft.fft2(img_float32)
        dft_shifted = np.fft.fftshift(dft)

        crow, ccol = h // 2, w // 2

        mask = np.zeros((h, w), np.uint8)

        for r in range(h):
            for c in range(w):
                if ((r - crow)**2 + (c - ccol)**2) < cutoff_radius**2:
                    mask[r, c] = 1

        fshift_lpf = dft_shifted * mask
        lpf_magnitude_spectrum = 20 * np.log(np.abs(fshift_lpf) + 1e-6)


        f_ishift = np.fft.ifftshift(fshift_lpf)

        img_back = np.fft.ifft2(f_ishift)

        img_lpf = np.abs(img_back)
        img_lpf = cv2.normalize(img_lpf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

        axes[idx, 0].imshow(img_gray, cmap='gray')
        axes[idx, 0].set_title(f"Örnek {idx+1} Gray- Orijinal\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(lpf_magnitude_spectrum, cmap='gray')
        axes[idx, 1].set_title("LPF Spektrumu")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_lpf, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} Gray- LPF Spektrum\n{row['label']}")
        axes[idx, 2].axis('off')

plt.tight_layout()
plt.show()

"""##6.3. Ters Fourier (Inverse FFT)"""

cutoff_radius = 40

iFFT_samples = random9_train_df

fig, axes = plt.subplots(9, 3, figsize=(15, 36))

for idx, (i, row) in enumerate(random9_train_df.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
        h, w = img_gray.shape

        img_float32 = np.float32(img_gray)
        dft = np.fft.fft2(img_float32)
        dft_shifted = np.fft.fftshift(dft)
        crow, ccol = h // 2, w // 2

        lpf_mask = np.zeros((h, w), np.uint8)
        for r in range(h):
            for c in range(w):
                if ((r - crow)**2 + (c - ccol)**2) < cutoff_radius**2:
                    lpf_mask[r, c] = 1
        hpf_mask = 1 - lpf_mask

        fshift_lpf = dft_shifted * lpf_mask
        f_ishift_lpf = np.fft.ifftshift(fshift_lpf)
        img_back_lpf = np.fft.ifft2(f_ishift_lpf)
        img_lpf = np.abs(img_back_lpf)
        img_lpf = cv2.normalize(img_lpf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

        fshift_hpf = dft_shifted * hpf_mask
        f_ishift_hpf = np.fft.ifftshift(fshift_hpf)
        img_back_hpf = np.fft.ifft2(f_ishift_hpf)
        img_hpf = np.abs(img_back_hpf)
        img_hpf = cv2.normalize(img_hpf, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

        axes[idx, 0].imshow(img_gray, cmap='gray')
        axes[idx, 0].set_title(f"Örnek {idx+1} Gray - Original\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(img_lpf, cmap='gray')
        axes[idx, 1].set_title(f"Örnek {idx+1} Gray - LPF (Yumuşak)\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_hpf, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} Gray - HDF (Keskin)\n{row['label']}")
        axes[idx, 2].axis('off')

plt.tight_layout()
plt.show()

"""#7. Keskinleştirme ve Enterpolasyon
##7.1. Unsharp Masking ile Keskinleştirme

"""

def apply_unsharp_mask(image, kernel_size=(5, 5), alpha=1.5):
    blurred = cv2.GaussianBlur(image, kernel_size, 0)
    sharpened = cv2.addWeighted(image, 1.0 + alpha, blurred, -alpha, 0)
    return sharpened

kernel_size = (5, 5)
alpha = 1.5

sample_limit = 9
usm_samples = random9_train_df

fig, axes = plt.subplots(9, 4, figsize=(18, 30))

for idx, (i, row) in enumerate(usm_samples.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        img_rgb_sharpened = apply_unsharp_mask(img_rgb, kernel_size, alpha)
        img_gray_sharpened = apply_unsharp_mask(img_gray, kernel_size, alpha)

        axes[idx, 0].imshow(img_rgb)
        axes[idx, 0].set_title(f"Örnek {idx+1} - RGB - Orijinal\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(img_rgb_sharpened)
        axes[idx, 1].set_title(f"Örnek {idx+1} - RGB - USM\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_gray, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} - GRAY - Orijinal\n{row['label']}")
        axes[idx, 2].axis('off')

        axes[idx, 3].imshow(img_gray_sharpened, cmap='gray')
        axes[idx, 3].set_title(f"Örnek {idx+1} - GRAY - USM\n{row['label']}")
        axes[idx, 3].axis('off')

plt.tight_layout()
plt.show()

"""##7.2. Bicubic Enterpolasyon


"""

scale_factor = 2

bicubic_samples = random9_train_df

fig, axes = plt.subplots(9, 4, figsize=(18, 30))

for idx, (i, row) in enumerate(bicubic_samples.iterrows()):
    img_path = row['file_path']
    img_bgr = cv2.imread(img_path)

    if img_bgr is not None:
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        img_rgb_usm = apply_unsharp_mask(img_rgb, kernel_size=(5,5), alpha=1.5)
        img_gray_usm = apply_unsharp_mask(img_gray, kernel_size=(5,5), alpha=1.5)

        h, w = img_rgb_usm.shape[:2]
        new_w, new_h = int(w * scale_factor), int(h * scale_factor)

        img_rgb_bicubic = cv2.resize(img_rgb_usm, (new_w, new_h), interpolation=cv2.INTER_CUBIC)
        img_gray_bicubic = cv2.resize(img_gray_usm, (new_w, new_h), interpolation=cv2.INTER_CUBIC)

        axes[idx, 0].imshow(img_rgb_usm)
        axes[idx, 0].set_title(f"Örnek {idx+1} - RGB - Original ({w}x{h})\n{row['label']}")
        axes[idx, 0].axis('off')

        axes[idx, 1].imshow(img_rgb_bicubic)
        axes[idx, 1].set_title(f"Örnek {idx+1} - RGB - Bicubic ({new_w}x{new_h})\n{row['label']}")
        axes[idx, 1].axis('off')

        axes[idx, 2].imshow(img_gray_usm, cmap='gray')
        axes[idx, 2].set_title(f"Örnek {idx+1} - GRAY - Original ({w}x{h})\n{row['label']}")
        axes[idx, 2].axis('off')

        axes[idx, 3].imshow(img_gray_bicubic, cmap='gray')
        axes[idx, 3].set_title(f"Örnek {idx+1} - GRAY - Bicubic ({new_w}x{new_h})\n{row['label']}")
        axes[idx, 3].axis('off')

plt.tight_layout()
plt.show()